name: Build and publish pre-release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.1xx
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --output Debug
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VictorKrogh.Extensions.Dapper
        path: "/home/runner/work/VictorKrogh.Extensions.Dapper/VictorKrogh.Extensions.Dapper/release/"

    - name: Push
      run: dotnet nuget push "release/VictorKrogh.Extensions.Dapper.1.0.0-dev-build.nupkg" --source https://nuget.pkg.github.com/VictorKroghDotNet/index.json --api-key ${TOKEN}
      env:
        TOKEN: ${{ secrets.TOKEN }}

    - name: AddOrUpdate release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN }}"
        automatic_release_tag: "pre-release"
        prerelease: true
        title: "Pre-release"
        files: "/home/runner/work/VictorKrogh.Extensions.Dapper/VictorKrogh.Extensions.Dapper/release/"
